site_name: RUN-DWC

theme:
  name: 'material'
  #custom_dir: overrides
  favicon: images/favicon.ico
  features:
    - content.code.copy
    - navigation.tabs
    #- navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
  #palette:
  #  - scheme: slate
  #    primary: light blue
  #    accent: yellow
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - attr_list
  - md_in_html
#extra_css:
#  - stylesheets/extra.css
